server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e106.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: message
          uri: lb://MESSAGE
          predicates:
            - Path=/message-service/**
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: article
          uri: lb://ARTICLE
          predicates:
            - Path=/article-service/**
          filters:
            - RewritePath=/article-service/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/search-service/**
          filters:
            - RewritePath=/search-service/(?<segment>.*), /$\{segment}
        - id: alarm
          uri: lb://ALARM
          predicates:
            - Path=/alarm-service/**
          filters:
            - RewritePath=/alarm-service/(?<segment>.*), /$\{segment}
        - id: personal
          uri: lb://PERSONAL
          predicates:
            - Path=/personal-service/**
          filters:
            - RewritePath=/personal-service/(?<segment>.*), /$\{segment}
        - id: group
          uri: lb://GROUP
          predicates:
            - Path=/group-service/**
          filters:
            - RewritePath=/group-service/(?<segment>.*), /$\{segment}
        - id: online-server
          uri: lb://ONLINE-SERVER
          predicates:
            - Path=/online-service/**
          filters:
            - RewritePath=/group-service/(?<segment>.*), /$\{segment}
