server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e106.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: message
          uri: lb://MESSAGE
          predicates:
            - Path=/message/**
          filters:
            - RewritePath=/message/(?<segment>.*), /$\{segment}
        - id: auth
          uri: lb://AUTHE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: article
          uri: lb://ARTICLE
          predicates:
            - Path=/article/**
          filters:
            - RewritePath=/article/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
