server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8e106.p.ssafy.io:8761/eureka


spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/message-service/**
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article-service/**
          filters:
            - RewritePath=/article-service/(?<segment>.*), /$\{segment}
