spring:
  profiles:
    active: secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jdbc.time_zone: Asia/Seoul

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k8e106.p.ssafy.io:3306/ppol?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

feign:
  url:
    base: http://k8e106.p.ssafy.io:8000/
    alarm:
      service: alarm-service/
      controller: alarms
    auth:
      service: auth-service/
      controller: auth